language: ruby
bundler_args: --without development
rvm:
    - 1.8.7
    - 1.9.3
    - ruby-head
script:
    - "bundle install"
    - "bundle exec rake lint"
    - "bundle exec rake spec SPEC_OPTS='--format documentation'"
env:
    - PUPPET_VERSION="~> 3.5"
    - PUPPET_VERSION="~> 3.7.2"
matrix:
    allow_failures:
        - rvm: ruby-head
gemfile: Gemfile
