language: ruby
rvm:
    - 1.8.7
    - 1.9.3
    - ruby-head
script:
    - "bundle exec rake spec"
env:
    - PUPPET_VERSION="~> 3.0.0"
    - PUPPET_VERSION="~> 3.1.0"
matrix:
    allow_failures:
        - rvm: ruby-head
gemfile: Gemfile